# fly.toml app configuration file generated for takoyaki-back on 2024-11-16T15:47:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'takoyaki-back'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
